version: '3.8'

services:
  # Next.js App
  neon-murer-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: neon-murer-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - neon-murer-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: neon-murer-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Für SSL Zertifikate (optional)
    networks:
      - neon-murer-network
    depends_on:
      - neon-murer-app

networks:
  neon-murer-network:
    driver: bridge

volumes:
  ssl-certs: 