version: '3.8'

services:
  neonmurer-website:
    image: ghcr.io/crypticbae/nm-new:latest
    container_name: neonmurer-website
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: neonmurer-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # Für SSL-Zertifikate (optional)
    depends_on:
      - neonmurer-website
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 