version: '3.8'

services:
  # Neon Murer AG Website
  neon-murer-web:
    image: ghcr.io/crypticbae/nm-new:latest
    container_name: neon-murer-website
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.neon-murer.rule=Host(`deine-domain.com`)"
      - "traefik.http.services.neon-murer.loadbalancer.server.port=3000"

  # Optional: Nginx Reverse Proxy (auskommentiert)
  # nginx:
  #   image: nginx:alpine
  #   container_name: neon-murer-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - neon-murer-web

networks:
  default:
    name: neon-murer-network 